services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hend
      - MONGO_INITDB_ROOT_PASSWORD=hend

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - mongo_data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hend
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hend
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - microservices-net
    command: "start-dev"
networks:
  microservices-net:
    driver: bridge

volumes:
  mongo_data:
  keycloak_data: