apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "companymicroservice.fullname" . }}
  labels:
    {{- include "companymicroservice.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "companymicroservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "companymicroservice.name" . }}
    spec:
      containers:
        - name: {{ include "companymicroservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
