pipeline {
    agent any
    tools { 
        jdk 'JAVA_HOME' 
        maven 'M2_HOME' 
    }
    stages {
        stage('GIT') {
            steps {
                git branch: 'main', url: 'https://github.com/FarahHend/C02Calculator.git'
            }
        }
        stage('Compile Stage') {
            steps {
                dir('/C02Calculator/CompanyService') {
                    sh 'mvn clean compile'
                }
            }
        }
    }
}
